; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:grovepi]
platform = atmelavr
board = uno
framework = arduino
upload_protocol = arduino
upload_port = COM6
monitor_speed = 115200
build_flags = 
	-DFW_VERSION_MAJOR=0
	-DFW_VERSION_MINOR=3
	-DFW_VERSION_PATCH=0
platform_packages = platformio/tool-avrdude@^1.60300.0

[env:isp]
platform = atmelavr
board = uno
framework = arduino
upload_protocol = usbtiny
board_hardware.oscillator = external
board_fuses.lfuse = 0xFF
board_fuses.hfuse = 0xD9
board_fuses.efuse = 0xFD
monitor_speed = 115200
build_flags = 
	-DFW_VERSION_MAJOR=0
	-DFW_VERSION_MINOR=3
	-DFW_VERSION_PATCH=0
platform_packages = platformio/tool-avrdude@^1.60300.0

[env:grovepi-mavlink]
extends = env:grovepi
build_flags = 
	-DFW_VERSION_MAJOR=0
	-DFW_VERSION_MINOR=3
	-DFW_VERSION_PATCH=0
	-DENABLE_MAVLINK
	-DMAVLINK_COMM_NUM_BUFFERS=1
	-I ../_common/protocol/mavlink/generated/c
platform_packages = platformio/tool-avrdude@^1.60300.0

[env:isp-mavlink]
extends = env:isp
build_flags = 
	-DFW_VERSION_MAJOR=0
	-DFW_VERSION_MINOR=3
	-DFW_VERSION_PATCH=0
	-DENABLE_MAVLINK
	-DMAVLINK_COMM_NUM_BUFFERS=1
	-I ../_common/protocol/mavlink/generated/c
platform_packages = platformio/tool-avrdude@^1.60300.0
